# Generated by Django 2.2.3 on 2020-03-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveleverywhere', '0004_auto_20200315_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
    ]
