# Generated by Django 2.2.3 on 2020-03-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveleverywhere', '0005_auto_20200318_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
