# Generated by Django 2.2.3 on 2020-03-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveleverywhere', '0008_auto_20200319_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='replies',
        ),
    ]
