# Generated by Django 2.2.3 on 2020-03-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveleverywhere', '0009_remove_question_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bodySummary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
