# Generated by Django 2.2.3 on 2020-03-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveleverywhere', '0010_blog_bodysummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bodySummary',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
