# Generated by Django 2.2.3 on 2020-03-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveleverywhere', '0011_auto_20200321_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bodySummary',
            field=models.CharField(max_length=200),
        ),
    ]
