# Generated by Django 2.2.3 on 2020-03-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveleverywhere', '0012_auto_20200321_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='rating',
        ),
        migrations.AddField(
            model_name='airline',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airline',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
