# Generated by Django 2.2.3 on 2020-03-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveleverywhere', '0013_auto_20200325_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='bookingwebsite',
            name='rating',
        ),
        migrations.AddField(
            model_name='agency',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agency',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingwebsite',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingwebsite',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
