# Generated by Django 2.2.3 on 2020-03-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveleverywhere', '0014_auto_20200325_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='bookingwebsite',
            old_name='user',
            new_name='users',
        ),
    ]
