# Generated by Django 2.2.3 on 2020-03-27 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traveleverywhere', '0017_auto_20200327_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookingwebsite',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='bookingwebsite',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='bookingwebsite',
            name='user',
        ),
        migrations.CreateModel(
            name='WebsiteLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveleverywhere.BookingWebsite')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveleverywhere.BookingWebsite')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveleverywhere.Agency')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveleverywhere.Agency')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
